run_name: scrna_to_vcc_diffusion
output_dir: checkpoints
seed: 42
device: cuda
amp_dtype: bf16
use_wandb: true
wandb_project: vcc-st-diffusion

model:
  model_class: models.diffusion:ConditionalDiffusionTransformer
  config_class: models.diffusion:ConditionalModelConfig
  config_args:
    dim: 640
    n_head: 16
    n_layer: 18
    ffn_mult: 4
    vocab_size: 128
    token_max_value: 9.2
    n_genes: 3000
    n_total_genes: 3000
    gene_embed_dim: 512
    n_technical_batches: 48
    batch_embed_dim: 40
    use_batch_conditioning: true
    control_set_encoder_layers: 2
    control_set_dim_hidden: 512
    n_timesteps: 16
    schedule: cosine
    pretrain_mask_ratio: 0.4
    finetune_mask_ratio_start: 0.4
    finetune_mask_ratio_end: 0.9
    finetune_mask_ratio_steps: 10000
    finetune_full_mask_prob: 0.05
    use_fp8: false

optimizer:
  optimizer_class: torch.optim.AdamW
  optimizer_args:
    lr: 1.0e-4
    weight_decay: 0.01

loss:
  loss_class: engine.losses:DiffusionLoss
  loss_args:
    diffusion_class: models.diffusion:PartialMaskingDiffusion

# Datasets stack with wrappers that compute HVGs/tokenizers internally
# Provide simple arguments only.
datasets:
  - name: scrna_pretrain
    dataloader_factory: wrappers.factories:create_scrna_pretrain
    dataloader_args:
      data_dir: /scRNA_norm/processed
      hvg_info_path: assets/hvg_seuratv3_3000.txt
      batch_size: 128
      num_workers: 4
      normalize: false
    epochs: 1
    log_every_steps: 100
    save_every_steps: 1500
    eval_every_epochs: 1

  - name: vcc_finetune
    dataloader_factory: wrappers.factories:create_vcc_finetune
    dataloader_args:
      adata_path: /competition_train.h5
      hvg_info_path: assets/hvg_seuratv3_3000.txt
      set_size: 128
      batch_size: 1
      n_samples_per_gene_train: 10
      n_samples_per_gene_val: 1
      train_split: 0.8
      num_workers: 4
      random_seed: 42
      normalize: false
      blacklist_path: assets/blacklist.txt
    epochs: 1
    log_every_steps: 100
    save_every_steps: 1500
    eval_every_epochs: 1